language: java
jdk:
- oraclejdk9
services:
- mysql
dist: trusty
sudo: required
addons:
apt:
packages:
- mysql-server-5.6
- mysql-client-core-5.6
- mysql-client-5.6
before_script:
- mysql -u root -e 'CREATE DATABASE human;'
- mysql -u root -e "CREATE USER 'sa'@'localhost' IDENTIFIED BY 'sa';"
- mysql -u root -e "GRANT ALL ON human.* TO 'sa'@'localhost';"
script: mvn package -Dmaven.test.skip=true 
deploy:
 provider: heroku
 api_key:
    secure: 1c11cbb5-6675-408b-91ff-dd2790e71f12
 app: back-spring

