language: java
jdk:
- oraclejdk9
services:
- mysql
dist: trusty
sudo: required
addons:
apt:
packages:
- mysql-server-5.6
- mysql-client-core-5.6
- mysql-client-5.6
before_script:
- mysql -u root -e 'CREATE DATABASE lab7;'
- mysql -u root -e "CREATE USER 'admin'@'localhost' IDENTIFIED BY 'admin';"
- mysql -u root -e "GRANT ALL ON lab7.* TO 'admin'@'localhost';"
before_install:
- chmod +x mvnw
deploy:
 provider: heroku
 api_key:
    secure: 1c11cbb5-6675-408b-91ff-dd2790e71f12
 app: back-spring

